import type { IconType } from 'react-icons';
import { GrStatusPlaceholder } from 'react-icons/gr';
import {
	WiCloudy,
	WiCloudyGusts,
	WiDayHaze,
	WiDaySunny,
	WiDust,
	WiFog,
	WiHail,
	WiHot,
	WiHurricane,
	WiLightning,
	WiMoonFirstQuarter,
	WiMoonFull,
	WiMoonNew,
	WiMoonThirdQuarter,
	WiMoonWaningCrescent1,
	WiMoonWaningCrescent2,
	WiMoonWaningCrescent3,
	WiMoonWaningCrescent4,
	WiMoonWaningCrescent5,
	WiMoonWaningCrescent6,
	WiMoonWaningGibbous1,
	WiMoonWaningGibbous2,
	WiMoonWaningGibbous3,
	WiMoonWaningGibbous4,
	WiMoonWaningGibbous5,
	WiMoonWaningGibbous6,
	WiMoonWaxing6,
	WiMoonWaxingCrescent1,
	WiMoonWaxingCrescent2,
	WiMoonWaxingCrescent3,
	WiMoonWaxingCrescent4,
	WiMoonWaxingCrescent5,
	WiMoonWaxingGibbous1,
	WiMoonWaxingGibbous2,
	WiMoonWaxingGibbous3,
	WiMoonWaxingGibbous4,
	WiMoonWaxingGibbous5,
	WiMoonWaxingGibbous6,
	WiNightClear,
	WiRain,
	WiRainMix,
	WiShowers,
	WiSleet,
	WiSmoke,
	WiSnow,
	WiSnowflakeCold,
	WiSprinkle,
	WiStormShowers,
	WiStrongWind,
	WiThunderstorm,
	WiTornado,
	WiWindy,
} from 'react-icons/wi';

export const OWM_TO_ICON: Record<string, IconType> = {
	'wi-owm-200': WiThunderstorm,
	'wi-owm-201': WiThunderstorm,
	'wi-owm-202': WiThunderstorm,
	'wi-owm-210': WiLightning,
	'wi-owm-211': WiLightning,
	'wi-owm-212': WiLightning,
	'wi-owm-221': WiLightning,
	'wi-owm-230': WiThunderstorm,
	'wi-owm-231': WiThunderstorm,
	'wi-owm-232': WiThunderstorm,
	'wi-owm-300': WiSprinkle,
	'wi-owm-301': WiSprinkle,
	'wi-owm-302': WiRain,
	'wi-owm-310': WiRainMix,
	'wi-owm-311': WiRain,
	'wi-owm-312': WiRain,
	'wi-owm-313': WiShowers,
	'wi-owm-314': WiRain,
	'wi-owm-321': WiSprinkle,
	'wi-owm-500': WiSprinkle,
	'wi-owm-501': WiRain,
	'wi-owm-502': WiRain,
	'wi-owm-503': WiRain,
	'wi-owm-504': WiRain,
	'wi-owm-511': WiRainMix,
	'wi-owm-520': WiShowers,
	'wi-owm-521': WiShowers,
	'wi-owm-522': WiShowers,
	'wi-owm-531': WiStormShowers,
	'wi-owm-600': WiSnow,
	'wi-owm-601': WiSnow,
	'wi-owm-602': WiSleet,
	'wi-owm-611': WiRainMix,
	'wi-owm-612': WiRainMix,
	'wi-owm-615': WiRainMix,
	'wi-owm-616': WiRainMix,
	'wi-owm-620': WiRainMix,
	'wi-owm-621': WiSnow,
	'wi-owm-622': WiSnow,
	'wi-owm-701': WiShowers,
	'wi-owm-711': WiSmoke,
	'wi-owm-721': WiDayHaze,
	'wi-owm-731': WiDust,
	'wi-owm-741': WiFog,
	'wi-owm-761': WiDust,
	'wi-owm-762': WiDust,
	'wi-owm-771': WiCloudyGusts,
	'wi-owm-781': WiTornado,
	'wi-owm-800': WiDaySunny,
	'wi-owm-801': WiCloudy,
	'wi-owm-802': WiCloudy,
	'wi-owm-803': WiCloudy,
	'wi-owm-804': WiCloudy,
	'wi-owm-900': WiTornado,
	'wi-owm-901': WiStormShowers,
	'wi-owm-902': WiHurricane,
	'wi-owm-903': WiSnowflakeCold,
	'wi-owm-904': WiHot,
	'wi-owm-905': WiWindy,
	'wi-owm-906': WiHail,
	'wi-owm-957': WiStrongWind,
	'wi-owm-day-200': WiThunderstorm,
	'wi-owm-day-201': WiThunderstorm,
	'wi-owm-day-202': WiThunderstorm,
	'wi-owm-day-210': WiLightning,
	'wi-owm-day-211': WiLightning,
	'wi-owm-day-212': WiLightning,
	'wi-owm-day-221': WiLightning,
	'wi-owm-day-230': WiThunderstorm,
	'wi-owm-day-231': WiThunderstorm,
	'wi-owm-day-232': WiThunderstorm,
	'wi-owm-day-300': WiSprinkle,
	'wi-owm-day-301': WiSprinkle,
	'wi-owm-day-302': WiRain,
	'wi-owm-day-310': WiRain,
	'wi-owm-day-311': WiRain,
	'wi-owm-day-312': WiRain,
	'wi-owm-day-313': WiRain,
	'wi-owm-day-314': WiRain,
	'wi-owm-day-321': WiSprinkle,
	'wi-owm-day-500': WiSprinkle,
	'wi-owm-day-501': WiRain,
	'wi-owm-day-502': WiRain,
	'wi-owm-day-503': WiRain,
	'wi-owm-day-504': WiRain,
	'wi-owm-day-511': WiRainMix,
	'wi-owm-day-520': WiShowers,
	'wi-owm-day-521': WiShowers,
	'wi-owm-day-522': WiShowers,
	'wi-owm-day-531': WiStormShowers,
	'wi-owm-day-600': WiSnow,
	'wi-owm-day-601': WiSleet,
	'wi-owm-day-602': WiSnow,
	'wi-owm-day-611': WiRainMix,
	'wi-owm-day-612': WiRainMix,
	'wi-owm-day-615': WiRainMix,
	'wi-owm-day-616': WiRainMix,
	'wi-owm-day-620': WiRainMix,
	'wi-owm-day-621': WiSnow,
	'wi-owm-day-622': WiSnow,
	'wi-owm-day-701': WiShowers,
	'wi-owm-day-711': WiSmoke,
	'wi-owm-day-721': WiDayHaze,
	'wi-owm-day-731': WiDust,
	'wi-owm-day-741': WiFog,
	'wi-owm-day-761': WiDust,
	'wi-owm-day-762': WiDust,
	'wi-owm-day-781': WiTornado,
	'wi-owm-day-800': WiDaySunny,
	'wi-owm-day-801': WiCloudy,
	'wi-owm-day-802': WiCloudy,
	'wi-owm-day-803': WiCloudy,
	'wi-owm-day-804': WiCloudy,
	'wi-owm-day-900': WiTornado,
	'wi-owm-day-902': WiHurricane,
	'wi-owm-day-903': WiSnowflakeCold,
	'wi-owm-day-904': WiHot,
	'wi-owm-day-906': WiHail,
	'wi-owm-day-957': WiStrongWind,
	'wi-owm-night-200': WiThunderstorm,
	'wi-owm-night-201': WiThunderstorm,
	'wi-owm-night-202': WiThunderstorm,
	'wi-owm-night-210': WiLightning,
	'wi-owm-night-211': WiLightning,
	'wi-owm-night-212': WiLightning,
	'wi-owm-night-221': WiLightning,
	'wi-owm-night-230': WiThunderstorm,
	'wi-owm-night-231': WiThunderstorm,
	'wi-owm-night-232': WiThunderstorm,
	'wi-owm-night-300': WiSprinkle,
	'wi-owm-night-301': WiSprinkle,
	'wi-owm-night-302': WiRain,
	'wi-owm-night-310': WiRain,
	'wi-owm-night-311': WiRain,
	'wi-owm-night-312': WiRain,
	'wi-owm-night-313': WiRain,
	'wi-owm-night-314': WiRain,
	'wi-owm-night-321': WiSprinkle,
	'wi-owm-night-500': WiSprinkle,
	'wi-owm-night-501': WiRain,
	'wi-owm-night-502': WiRain,
	'wi-owm-night-503': WiRain,
	'wi-owm-night-504': WiRain,
	'wi-owm-night-511': WiRainMix,
	'wi-owm-night-520': WiShowers,
	'wi-owm-night-521': WiShowers,
	'wi-owm-night-522': WiShowers,
	'wi-owm-night-531': WiStormShowers,
	'wi-owm-night-600': WiSnow,
	'wi-owm-night-601': WiSleet,
	'wi-owm-night-602': WiSnow,
	'wi-owm-night-611': WiRainMix,
	'wi-owm-night-612': WiRainMix,
	'wi-owm-night-615': WiRainMix,
	'wi-owm-night-616': WiRainMix,
	'wi-owm-night-620': WiRainMix,
	'wi-owm-night-621': WiSnow,
	'wi-owm-night-622': WiSnow,
	'wi-owm-night-701': WiShowers,
	'wi-owm-night-711': WiSmoke,
	'wi-owm-night-721': WiDayHaze,
	'wi-owm-night-731': WiDust,
	'wi-owm-night-741': WiFog,
	'wi-owm-night-761': WiDust,
	'wi-owm-night-762': WiDust,
	'wi-owm-night-781': WiTornado,
	'wi-owm-night-800': WiNightClear,
	'wi-owm-night-801': WiCloudy,
	'wi-owm-night-802': WiCloudy,
	'wi-owm-night-803': WiCloudy,
	'wi-owm-night-804': WiCloudy,
	'wi-owm-night-900': WiTornado,
	'wi-owm-night-902': WiHurricane,
	'wi-owm-night-903': WiSnowflakeCold,
	'wi-owm-night-904': WiHot,
	'wi-owm-night-906': WiHail,
	'wi-owm-night-957': WiStrongWind,
};

export const getWeatherIcon = (weatherCode: number, icon: string) => {
	const mode = icon.endsWith('d') ? '-day' : icon.endsWith('n') ? '-night' : '';
	const key = `wi-owm${mode}-${weatherCode}`;
	return OWM_TO_ICON[key] || GrStatusPlaceholder;
};

export const MOON_PHASES = [
	{ Icon: WiMoonNew, label: 'New' },
	{ Icon: WiMoonWaxingCrescent1, label: 'Waxing Crescent' },
	{ Icon: WiMoonWaxingCrescent2, label: 'Waxing Crescent' },
	{ Icon: WiMoonWaxingCrescent3, label: 'Waxing Crescent' },
	{ Icon: WiMoonWaxingCrescent4, label: 'Waxing Crescent' },
	{ Icon: WiMoonWaxingCrescent5, label: 'Waxing Crescent' },
	{ Icon: WiMoonWaxing6, label: 'Waxing Crescent' },
	{ Icon: WiMoonFirstQuarter, label: 'First Quarter' },
	{ Icon: WiMoonWaxingGibbous1, label: 'Waxing Gibbous' },
	{ Icon: WiMoonWaxingGibbous2, label: 'Waxing Gibbous' },
	{ Icon: WiMoonWaxingGibbous3, label: 'Waxing Gibbous' },
	{ Icon: WiMoonWaxingGibbous4, label: 'Waxing Gibbous' },
	{ Icon: WiMoonWaxingGibbous5, label: 'Waxing Gibbous' },
	{ Icon: WiMoonWaxingGibbous6, label: 'Waxing Gibbous' },
	{ Icon: WiMoonFull, label: 'Full' },
	{ Icon: WiMoonWaningGibbous1, label: 'Waning Gibbous' },
	{ Icon: WiMoonWaningGibbous2, label: 'Waning Gibbous' },
	{ Icon: WiMoonWaningGibbous3, label: 'Waning Gibbous' },
	{ Icon: WiMoonWaningGibbous4, label: 'Waning Gibbous' },
	{ Icon: WiMoonWaningGibbous5, label: 'Waning Gibbous' },
	{ Icon: WiMoonWaningGibbous6, label: 'Waning Gibbous' },
	{ Icon: WiMoonThirdQuarter, label: 'Third Quarter' },
	{ Icon: WiMoonWaningCrescent1, label: 'Waning Crescent' },
	{ Icon: WiMoonWaningCrescent2, label: 'Waning Crescent' },
	{ Icon: WiMoonWaningCrescent3, label: 'Waning Crescent' },
	{ Icon: WiMoonWaningCrescent4, label: 'Waning Crescent' },
	{ Icon: WiMoonWaningCrescent5, label: 'Waning Crescent' },
	{ Icon: WiMoonWaningCrescent6, label: 'Waning Crescent' },
];

export const getMoonPhaseIcon = (moon_phase: number) => {
	const index = Math.round(moon_phase * (MOON_PHASES.length - 1));
	return MOON_PHASES[index];
};
